src/auth/auth.controller.ts
- 로그인 여부를 확인할 수 있는 URI를 추가하였습니다.
- #2
=> feat: #2 add login check endpoint

src/app.module.ts, src/tag-log-v1/dto/MainInfo.type.ts, src/tag-log-v1/dto/UserInOutLogs.type.ts, src/tag-log-v1/dto/subType/InOutLog.type.ts, src/tag-log-v1/dto/subType/UserAccumulation.type.ts, src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.module.ts
- 프론트앤드와 데이터 포맷을 미리 맞춰보기 위해 컨트롤러를 만들었습니다. 현재는 특정 날짜에 대한 누적 사용량만 출력합니다.
- #7
=> 컨트롤러 형태 지정 및 목업 데이터 주입

.github/workflows/cd.yaml
- CD를 위한 GitHub Actions 설정을 하였습니다.
- 
- #5
=> CD Setting

.env.sample, src/main.ts
- cors 설정이 환경변수가 설정되어 있을 때 그 환경변수에 대해 동작되도록 변경하였습니다.
- #17
=> fix: #17 enable cors

src/auth/auth.controller.ts
- islogin이 로그인 되어있을 때 204를 리턴하도록 수정
- #19
=> fix: #19 islogin http response code

src/entities/card-issuance.entity.ts, src/entities/device-info.entity.ts, src/entities/pair-info.entity.ts, src/entities/tag-log.entity.ts, src/entities/user-info.entity.ts, src/tag-log-v1/dto/pair-info.dto.ts, src/tag-log-v1/dto/tag-log.dto.ts, src/tag-log-v1/repository/interface/pair-info-repository.interface.ts, src/tag-log-v1/repository/interface/tag-log-repository.interface.ts, src/tag-log-v1/repository/interface/user-info-repository.interface.ts, src/tag-log-v1/repository/mysql/pair-info.repository.ts, src/tag-log-v1/repository/mysql/tag-log.repository.ts, src/tag-log-v1/repository/mysql/user-info.repository.ts, src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.module.ts, src/tag-log-v1/tag-log.service.ts
- 엔티티를 DDL에 맞게 수정하였습니다.
- 리포지토리 패턴을 적용하였습니다.
- #15
=> feat: #15 fix entities & add repository pattern

src/auth/42/user.session.dto.ts, src/tag-log-v1/dto/admin/user-accumulation-day.type.ts, src/tag-log-v1/dto/admin/user-accumulation-month-day.type.ts, src/tag-log-v1/dto/admin/user-accumulation-month.type.ts, src/tag-log-v1/dto/admin/user-id.type.ts, src/tag-log-v1/repository/interface/user-info-repository.interface.ts, src/tag-log-v1/repository/mysql/user-info.repository.ts, src/tag-log-v1/tag-log-admin.controller.ts, src/tag-log-v1/tag-log-admin.service.ts, src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.module.ts
- doosoo 팀장님이 요청하신 HTTP API (목업)을 만들었습니다.
- 추가로 세션 DTO도 만들었습니다.
- #27
=> feat: #27 add admin API & add user session dto

.env.sample, package-lock.json, package.json, src/auth/auth.controller.ts, src/auth/auth.module.ts, src/configs/configuration.ts, src/utils/google-api.component.ts, src/utils/utils.module.ts
- 리다이렉트 URI 없이 로그인을 시도할 때, 어드민 계정이라면 구글 시트에 토큰을 송부하게 하였습니다.
- #33
=> feat: add google API

src/entities/user-info.entity.ts, src/tag-log-v1/repository/interface/pair-info-repository.interface.ts, src/tag-log-v1/repository/interface/tag-log-repository.interface.ts, src/tag-log-v1/repository/mysql/pair-info.repository.ts, src/tag-log-v1/repository/mysql/tag-log.repository.ts, src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.service.ts, src/usage/usage.controller.ts, src/webhook/webhook.module.e2e-spec.ts
- 가장 최근의 로그를 가져와서 사용자가 현재 클러스터에 존재하는지의 여부를 판단하게 함.
- #38
=> 사용자가 현재 클러스터에 존재하는지의 여부 판단 로직 추가

src/tag-log-v1/repository/interface/tag-log-repository.interface.ts, src/tag-log-v1/repository/mysql/tag-log.repository.ts, src/tag-log-v1/tag-log.service.ts
- 가져오고자 하는 날짜 범위의 전후로 해당 날짜 경계의 00시, 24시로 가상 입출입 기록을 추가하여 산정 누락 방지처리
- #37
=> feat: #37 가져오고자 하는 날짜 범위 전후로 가상 입출입 기록 추가

src/auth/auth.controller.ts
=> feat: #43 add logout api

src/auth/auth.controller.ts
=> fix: #46 apply encodeURI @ session

src/app.module.ts
=> refactor: middleware

src/app.module.ts, src/tag-log-v1/dto/id-login.dto.ts, src/tag-log-v1/tag-log-admin.service.ts, src/tag-log-v1/tag-log.module.ts, src/tag-log-v1/tag-log.service.ts, src/user/dto/id-login.dto.ts, src/user/repository/interface/user-info-repository.interface.ts, src/user/repository/mysql/user-info.repository.ts, src/user/user.module.ts, src/user/user.service.ts, src/user/user.v1.controller.ts
- [리팩터링] user 관련 기능은 user 모듈에 만들어 삽입하였습니다.
- [신규기능] #53
- #53
=> feat: #53 add user modules & controller

src/app.module.ts, src/tag-log-v1/dto/id-login.dto.ts, src/tag-log-v1/tag-log-admin.service.ts, src/tag-log-v1/tag-log.module.ts, src/tag-log-v1/tag-log.service.ts, src/user/dto/id-login.dto.ts, src/user/repository/interface/user-info-repository.interface.ts, src/user/repository/mysql/user-info.repository.ts, src/user/user.module.ts, src/user/user.service.ts, src/user/user.v1.controller.ts
=> develop to main

src/tag-log-v1/dto/inout.dto.ts, src/tag-log-v1/dto/user-Info.type.ts, src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.service.ts
- UserInfoType 리스폰스에 tagAt 추가
- #56
=> feat: #56 add tag log

src/tag-log-v1/tag-log.service.ts
=> HOTFIX: 집현전 예외처리

src/auth/guard/jwt-sign.guard.ts, src/tag-log-v1/tag-log-admin.controller.ts
- 쿠키 URI Request의 Host에서 가져오도록 함
- swagger 명세 변경
=> fix: cookie uri, swagger

src/app.module.ts, src/auth/auth.module.ts, src/auth/guard/ext-auth.guard.ts, src/auth/srategy/auth.external.strategy.ts, src/entities/device-info.entity.ts, src/ext/dto/device.dto.ts, src/ext/dto/where42.response.dto.ts, src/ext/ext.module.ts, src/ext/ext.service.ts, src/ext/repository/interface/device-info.repository.interface.ts, src/ext/repository/mysql/device-info.repository.ts, src/ext/where42.controller.ts
- Where42 API 추가 & 인증 추가
- #83
=> Where42 API 추가

src/tag-log-v1/tag-log.service.ts
- 유튜브 스튜디오 출입내역을 예외에 추가하였습니다.
- #87 (@kreativemoon 님의 요청)
=> hotfix: #87

src/configs/configuration.ts, src/main.ts
- nest config 설정을 nest 모듈 외부에서 가져오도록 변경하였습니다.
- #82
=> refactor: #82 main.ts에서 nest config 설정 가져오도록

src/auth/guard/jwt-sign.guard.ts
- 쿠키 만료기간 설정 (JWT 만료기간에 맞춤)
- #97
=> fix: #97 set cookie expire

src/ext/ext.service.ts, src/tag-log-v1/repository/interface/tag-log-repository.interface.ts, src/tag-log-v1/repository/mysql/tag-log.repository.ts, src/tag-log-v1/tag-log.service.ts
=> #103 fix where query

package-lock.json, src/tag-log-v1/dto/subType/InOutLog.type.ts, src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.service.ts
- controller: getAllTagPerDay, service: getAllPairsByTagLogs 함수 작성
- 디바이스 개별 확인을 위한 isInDevice와 isOutDevice 함수 작성
- 짝이 맞지 않는 태그로그도 전해주는 함수 필요
=> feat: #109 all tag log

src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.service.ts
- 6개월어치 최종 산정 시간을 초단위(dto아니고 그냥 number)로 반환하는 함수를 추가했습니다.
- api이름은 getSixMonth이긴한데, service함수에서는 n을 인자로 받아 n개월만큼의 number를 반환하는 식으로 만들었습니다.
- 프론트 짱!
- 그냥 number로 했는데, dto를 만들어야할지... 고민입니다.
=> feat: #112 getSixMonth 추가

src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.service.ts, src/utils/date-calculator.component.ts
- 년도와 주차에 따라 산정시간을 반환하는 함수를 추가하였습니다. (number only)
=> feat: #114 get per week 추가

package-lock.json, package.json, src/app.module.ts, src/statistics/dto/cadet-per-cluster.dto.ts, src/statistics/repository/interface/statistics.repository.interface.ts, src/statistics/repository/mysql/statistics.repository.ts, src/statistics/statictics.controller.ts, src/statistics/statictics.module.ts, src/statistics/statictics.service.ts
- 클러스터의 현 인원을 체크할 수 있는 API를 추가하였습니다.
- #108
=> feat: #108 add statistics & cache

src/statistics/statictics.module.ts, src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.module.ts
- maininfo 엔드포인트에 개포/서초 인원 추가하였습니다.
- #108
=> fix: #108 add cluster info

package-lock.json, src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.service.ts
- 서비스 단의 중복 로직을 하나의 함수로 통합 -> getAllTagLogsByPeriod
- 태그로그를 필터링하는 과정에서 IN/OUT 이외 태그를 DEVICE_INFO 테이블 정보를 참고해 필터링
```
const filteredTagLogs = sortedTagLogs.filter(
taglog => !!(devicePairs.find(temp => temp.in_device === taglog.device_id || temp.out_device === taglog.device_id))
);
```
- in device, out device를 판별하는 과정에서 forEach 메소드를 find 로 교체
```
const inDevice = deviceInfos.find(deviceInfo => deviceInfo.in_device === targetDevice);
if (inDevice) {
return true;
}
return false;
```
=> refactor: #122 이슈 관련 여러 리팩토링 진행

src/tag-log-v1/tag-log.controller.ts
- maininfo에 개포/서초 인원현황을 추가하는 코드를 추가했었었는데, 어느 순간 유실되어 다시 추가하였습니다.
=> fix: add Statistics in maininfo

src/reissue/dto/reissueFinished.type.ts, src/reissue/reissue.controller.ts, src/reissue/reissue.service.ts, src/utils/google-api.component.ts
- 카드 재발급 신청 상태를 5가지로 변경 (신청내역 없음, 신청, 제작중, 제작완료, 완료)
- 사용자 카드 재발급 신청 내역이 없을 경우 status 성공으로 변경(신청내역 없음)
- 사용자가 카드 재발급 신청한 경우 (신청)
- 스태프가 재발급 신청내역 확인 후 (제작중)
- 상황별 status code 확인 (swagger문서와 실제 코드번호가 맞지않음)
- 카드 재발급 신청 POST -> status code 201로 수정
=> refactor: #124 카드 재발급 api 수정

src/tag-log-v1/tag-log.controller.ts
- maininfo에서 개포/서초 인원이 존재하지 않을 때 0이라도 출력하게 수정하였습니다.
=> fix: maininfo

src/tag-log-v1/tag-log.service.ts
=> fix: #117 마지막 날 구하는 방법 변경

src/app.module.ts, src/reissue/reissue.controller.ts, src/statistics/statictics.controller.ts, src/tag-log-v1/dto/user-accumulation.type.ts, src/tag-log-v1/tag-log-admin.controller.ts, src/tag-log-v1/tag-log-admin.service.ts, src/tag-log-v1/tag-log.controller.ts, src/tag-log-v1/tag-log.service.ts, src/tag-log-v2/dto/UserInOutLogs.type.ts, src/tag-log-v2/dto/admin/user-accumulation-day.type.ts, src/tag-log-v2/dto/admin/user-accumulation-month-day.type.ts, src/tag-log-v2/dto/admin/user-accumulation-month.type.ts, src/tag-log-v2/dto/admin/user-id.type.ts, src/tag-log-v2/dto/inout.dto.ts, src/tag-log-v2/dto/pair-info.dto.ts, src/tag-log-v2/dto/subType/InOutLog.type.ts, src/tag-log-v2/dto/tag-log.dto.ts, src/tag-log-v2/dto/user-Info.type.ts, src/tag-log-v2/dto/user-accumulation.type.ts, src/tag-log-v2/repository/interface/pair-info-repository.interface.ts, src/tag-log-v2/repository/interface/tag-log-repository.interface.ts, src/tag-log-v2/repository/mysql/pair-info.repository.ts, src/tag-log-v2/repository/mysql/tag-log.repository.ts, src/tag-log-v2/tag-log-v2.controller.ts, src/tag-log-v2/tag-log-v2.module.ts, src/tag-log-v2/tag-log-v2.service.ts
- 새로운 함수는 v2로 나누었습니다.
- 수정된 함수는 v1와 v2 두 가지 버전이 존재합니다.
- 내부적으로 동일하게 사용하는 함수가 개선된 경우 우선은 v1과 v2를 다르게 두었습니다. (중복로직을 함수로 뺀 경우 등...)
=> refactor: #131 v2 분리

src/app.module.ts, src/configs/configuration.ts, src/redirect/redirect.controller.ts, src/redirect/redirect.module.ts, src/redirect/redirect.service.ts
- #130 에 명세한대로 리다이렉트 API를 추가하였습니다. EC2 dev/main env에 해당 URI 추가해두었습니다.
- #130
=> feat: #130 add redirect module

.env.sample, src/configs/configuration.ts, src/redirect/redirect.controller.ts, src/redirect/redirect.service.ts
- 이용 약관, 재발급 가이드라인 URI를 추가하였습니다.
- #130 이슈에 대한 추가 요청
=> feat: #130 add URI & env samples

src/reissue/reissue.service.ts
- 잔디 알림 실패시 error log/ 응답 성공200
- 해당 내용 미반영
=> feat: #134 카드재발급 exception처리 수정(recommit)

src/enums/reissue-state.enum.ts, src/reissue/dto/finished.dto.ts, src/reissue/dto/finished.type.ts, src/reissue/dto/reissueState.dto.ts, src/reissue/dto/request.dto.ts, src/reissue/dto/request.type.ts, src/reissue/dto/state.dto.ts, src/reissue/dto/state.type.ts, src/reissue/reissue.controller.ts, src/reissue/reissue.service.ts
- reissueSateDto string -> enum 사용
- 파일명, 클레스이름 네이밍 컨벤션에 맞춰 수정
=> refactor: #136 reissue 모듈 리팩터링(enum 사용, 네이밍 컨벤션)

.gitignore, src/tag-log-v1/tag-log.service.ts, src/tag-log-v2/tag-log-v2.service.ts
- #148
- 분명 있었던 가상로그 추가 로직이... 없어져 있었네요 😞 
- 커밋 뒤로 돌려 다시 살려왔습니다!
- 밤샌 카뎃의 로그 기준으로 문제 없는것을 확인했습니다.
- 문제 있을시 핫픽스
=> fix: #148 virtual logs

src/tag-log-v2/tag-log-v2.service.ts
`getAllPairsByTagLogs` 에러로 인한 문제 발생으로 인한 revert
=> Revert "Develop to main"

src/tag-log-v2/tag-log-v2.service.ts
- #148
- 두번째 pop에서 length <= 0 으로 break조건이었던것을 pop하는 순간에 0보다 큰지 확인하는 것으로 변경하였습니다.
```
if (temp === null && timeLines.length > 0) {
temp = timeLines.pop();
} else {
break;
}
```
- 첫번째 pop은 아무리 생각해도 temp가 null인지 체크하는 부분이 while문에서 걸리는 length>0가 있기 때문에 확인할 이유가 없어 제외하였습니다.
- 나머지는 prettier적용 변경입니다.
- 자주 사용하는 테스트코드를 주석으로 함께 올렸습니다.
- 문의 들어오신 분들과 주변 밤새신 분들 로그로 확인 완료했습니다.
😢 잘되길
=> fix: #148 condition of pop

src/tag-log-v2/tag-log-v2.service.ts
- 지웠던 if문을 다시 추가했습니다. 2월달 이전의 2번씩 기록되던 로그를 판단하기 위한 로직이었네요.
- 2번씩 기록되던 2월초와 정상기록되던 2월 중순~말 로그가 잘 매치되는지 확인하였고, 월단위와 일단위 가상로그도 정상적으로 들어가는 것을 확인했습니다.
- 이외 accumulation함수도 확인했습니다.
- 테스트코드 주석은... 완전히 문제가 사라지면 지우겠습니다. 또 필요해지지 않기를 ...!! 🙏
=> fix: #148 add condition that deleted, add logging code

.github/workflows/cicd.yaml, package.json, src/tag-log-v2/tag-log-v2.service.spec.ts
- 기존 문의가 들어왔던 상황의 일부를 사용하여 테스트 케이스를 추가하였습니다.
- 로직 변경에 따른 사이드 이펙트를 방지하고, 구현할 사양을 명확하게 하기 위함.
=> getAllPairsByTagLogs unit test 추가

src/tag-log-v2/tag-log-v2-admin.controller.ts, src/tag-log-v2/tag-log-v2-admin.service.ts, src/tag-log-v2/tag-log-v2.module.ts
- tag-log-v2-admin.service.ts, tag-log-v2-admin.controller.ts 추가
=> feat:#174 add tag-log-v2 for admin

src/tag-log-v2/tag-log-v2.service.ts
=> fix: #178 missed virtual Logs

src/auth/srategy/auth.external.strategy.ts, src/tag-log-v2/tag-log-v2-cabi.controller.ts, src/tag-log-v2/tag-log-v2-cabi.service.ts, src/tag-log-v2/tag-log-v2.module.ts
사물함 대여 서비스 cabi에서 부탁한 카뎃 별 일일 출입시간 api 작업입니다
=> feat #177 cabi api

src/message-generator/message-generator.component.ts, src/tag-log/dto/user-Info.type.ts
- 공지 메세지 형식 지정 변경
- key : value(title, body 객체)형태로 변경
- 프론트의 요청
=> fix: change message form
